# REF: https://starship.rs/

# REF: https://starship.rs/config/#prompt
command_timeout = 10000

# REF: https://starship.rs/config/
[package]
disabled = true

# REF: https://starship.rs/config/#status
[status]
disabled = false

# REF: https://starship.rs/config/#git-status
[git_status]
conflicted = "ğŸ‘¿"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
deleted = "ğŸ—‘"
